; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32]
platform = espressif32@6.10.0
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
lib_ldf_mode = deep+
upload_protocol = esptool
upload_port = /dev/ttyUSB0
lib_deps =
  bodmer/TFT_eSPI@^2.5.43
  crankyoldgit/IRremoteESP8266@^2.8.6
  mathertel/RotaryEncoder@^1.5.3
  arduino-libraries/ArduinoHttpClient@^0.6.1
build_flags =
  -DUSER_SETUP_LOADED=1
  -DST7796_DRIVER=1
  -DTFT_WIDTH=320
  -DTFT_HEIGHT=480
  -DTFT_MOSI=13
  -DTFT_SCLK=14
  -DTFT_MISO=12
  -DTFT_CS=15
  -DTFT_DC=27
  -DTFT_RST=26
  -DTFT_BL=25
  -DTFT_BACKLIGHT_ON=1
  -DSPI_FREQUENCY=40000000
  -DSPI_READ_FREQUENCY=20000000
  -DLOAD_GLCD=1
  -DLOAD_FONT2=1
  -DLOAD_FONT4=1
  -DLOAD_GFXFF=1
  -DSMOOTH_FONT=1
  -DUSE_HSPI_PORT=1
  -D_IR_ENABLE_DEFAULT_=false
  -DDECODE_NEC=1
  -DDECODE_MITSUBISHIHEAVY=1
  -DSEND_NEC=1
  -DSEND_MITSUBISHIHEAVY=1
